# azure-pipelines.yml (in each repo)
resources:
  repositories:
    - repository: templates
      type: git
      name: APi Connect Continuous Improvement/pipeline-templates  # Replace with the actual name of your template repository

extends:
  template: github-cloning-pipelines-template.yml@templates
  parameters:
    repoName: $(Build.Repository.Name)
    branchName: $(Build.SourceBranchName)